# -*- coding: utf-8 -*-
"""Untitled62.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uQ5ILowl96FIvuXNkHBqHivzVdUINL3w
"""

import pandas as pd

df = pd.read_csv(r"/content/countries of the world.csv")

df

df = pd.read_table(r"/content/countries of the world.csv", sep = ',')
df

df = pd.read_json(r"/content/json_sample.json")
df

df2 = pd.read_excel(r"/content/world_population_excel_workbook (1).xlsx", sheet_name = 'Sheet1')
df2

pd.set_option('display.max.rows', 235)
pd.set_option('display.max.columns', 40)

df2.info()

df2.shape

df2.head(10)

df2.tail(10)

df2['Rank']

# Print the column names of the DataFrame to verify the correct column name
print(df2.columns)

# Once the correct column name is identified, replace 'Country' with the actual column name in the set_index method.
# For example, if the column is named 'Country Name', you would use:
# df2 = df2.set_index('Country Name')
# df2.loc['Uzbekistan']

# If you are confident that 'Country' is the correct name but there might be leading/trailing spaces,
# you can clean up the column names before setting the index.
# df2.columns = df2.columns.str.strip()
# df2 = df2.set_index('Country')
# df2.loc['Uzbekistan']

# The original code with the potentially incorrect column name:
# df2 = df2.set_index('Country') # Commenting out the problematic line

# --- INSERT THE CORRECTED CODE BELOW ---
# Based on the output of print(df2.columns), replace 'Your_Correct_Country_Column' with the actual column name
# Example:
# df2 = df2.set_index('Your_Correct_Country_Column')

# Once the index is set correctly, you can then use .loc
# df2.loc['Uzbekistan']

# If you need to strip spaces first:
# df2.columns = df2.columns.str.strip()
# df2 = df2.set_index('Your_Correct_Country_Column') # Use the potentially stripped column name
# df2.loc['Uzbekistan']

# Example based on a common column name 'Country/Territory' from similar datasets
# df2 = df2.set_index('Country/Territory')
# df2.loc['Uzbekistan']

df2.iloc[224]